version: '3'

services:
  # frontend
  dolores:
    image: mapleimage123/rap2-dolores:1.0.1
    ports:
      #冒号前可以自定义前端端口号，冒号后不要动
      - 38081:38081

  # backend
  delos:
    image: mapleimage123/rap2-delos:1.0.1
    ports:
      # 这里的配置不要改哦
      - 38080:38080
    environment:
      - SERVE_PORT=38080
      - MYSQL_URL=maple-mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWD=
      - MYSQL_SCHEMA=RAP2_DELOS_APP
      # redis config
      - REDIS_URL=maple-redis
      - REDIS_PORT=6379
      # production / development
      - NODE_ENV=production
    ###### 'sleep 30 && node scripts/init' will drop the tables
    ###### RUN ONLY ONCE THEN REMOVE 'sleep 30 && node scripts/init'
    command: /bin/sh -c 'node dispatch.js'
    # init the databases
    # command: sleep 30 && node scripts/init && node dispatch.js
    # without init
    # command: node dispatch.js
networks:
  default:
    external:
      # command: 指定已经存在的network
      name: maple-network
